### ISSUE TITLE
[QUESTION] How can I render children nodes inside their parents?

### ISSUE THREAD

**Issue by sfehlandt** [Lodin/react-vtree#10]
Hi, I have been trying to make a virtualized material-ui TreeView. I am trying to use react-vtree but in order to make it work I need to render children nodes inside their parent. E.g:

```
<TreeItem>
  <TreeItem>
    <TreeItem>
    </TreeItem>
  </TreeItem>
  <TreeItem>
    <TreeItem>
    </TreeItem>
  </TreeItem>
</TreeItem>
```

Is there anyway I can achieve this? As far as I can see, your examples render all the elements in the same level (like a list).

Thanks

**Comment by Lodin** [comment]
Hi @sfehlandt!

Thank you for your interest in `react-vtree`!

Unfortunately, I don't think it is possible. The virtualization approach assumes that you render a list of flat elements; the system knows the height of each element and basing on it and the height of the container calculates the number of elements to display ([read more](https://web.dev/virtualize-long-lists-react-window/)). Nested elements would break that system completely.

I'm afraid you would need to find a component that does not depend on nested elements or create it by your own.

**Comment by sfehlandt** [comment]
Thanks @Lodin , I understand. I think I'll try to build my own component and replicate the looks of the material-ui TreeView but keeping it as a list.

Thank you very much for your reply.
