### ISSUE TITLE
Opening a node programatically

### ISSUE THREAD

**Issue by kmrsfrnc** [Lodin/react-vtree#21]
How would you open a node programatically? I'm using a scrollToItem method and I would like to open the parent nodes if the item is not visible. I would map the parent ids to the item id, so just need to open the nodes based on the ids I have.

Good job with the library!

**Comment by woollsta** [comment]
I got this to work by setting the isOpenByDefault value inside the treeWalker to true if that item is in the array of ids I have in my local state, then I had a useEffect trigger when that array of ids changed to call recomputeTree.

Example:

```js
const [openItems, setOpenItems] = useState([]);
const treeRef = useRef();

const treeWalker = useMemo(() => {
    return function* treeWalkerFn(refresh) {
        ...
       const isOpened = yield refresh
          ? ({
              id: node.id,
              isOpenByDefault: openItems.includes(node.id),
           })
          : node.id;
        ...
    }
}, [openItems]);

useEffect(() => {
    if (treeRef.current){
        treeRef.current.recomputeTree({
           refreshNodes: true,
           useDefaultOpenness: true
        })
    }
}, [openItems]);

return (
    <FixedSizedTree
       ref={treeRef}
       treeWalker={treeWalker}
    />
);

```

**Comment by Lodin** [comment]
Hi @kmrsfrnc, sorry for the late response.

Unfortunately, there is no easy way to do it. You may use the approach @woollsta suggested, but it will probably close all elements opened by the user unless you track them in the `openItems` array manually.

I'm going to mark this issue as a feature request and implement a solution when I have time. Thanks for your contribution!
