### ISSUE TITLE
VariableSizeTree height does not behave as expected from upgrading to v2.0.0

### ISSUE THREAD

**Issue by ctan1345** [Lodin/react-vtree#25]
I have a use case where the parent's height is different from the children's height. This was working fine in v1.0.2. However, after upgrading to v2.0.0 all the elements seem to be the same as the parent's height.

After some investigation, it looks like `getItemSize()` is not being called after toggle. This is due to `lastMeasuredIndex` in `VariableSizeList` in `react-window` is not reset to -1 after children are added to the records (which is the case in the v1.0.2).

Adding `resetAfterId(record.data.id, true)` in `toggle()` resolves the issue. Just wondering if there is a proper fix for this issue. I can provide code examples if this is not clear. Thanks!

**Comment by Lodin** [comment]
@ctan1345, thanks for your contribution! I confirm the bug and going to release the fix ASAP.

**Comment by Lodin** [comment]
Released in [v2.0.1](https://github.com/Lodin/react-vtree/releases/tag/2.0.1).
Please check if it solves your issue. Thanks!

**Comment by ctan1345** [comment]
@Lodin Thanks for the quick response!

It worked when I call `toggle()`. However, the issue still exists when I expand the nodes via `recomputeTree()` with `opennessState`.

**Comment by Lodin** [comment]
@ctan1345, hmm, could you provide a little repro then? It would be easier to track the issue

**Comment by ctan1345** [comment]
Yes here is a small example: https://github.com/ctan1345/react-vtree-height-issue

When you click `-` on **Child #1** then click `Expand by recompute tree`, you can see the height of **Child #2** is not set properly.

Whereas when you expand via `toggle()`, it behaves as expected since your last fix.

**Comment by Lodin** [comment]
@ctan1345, I have released the [v2.0.2](https://github.com/Lodin/react-vtree/releases/tag/2.0.2); it should fix the issue. Could you check it please?

**Comment by ctan1345** [comment]
@Lodin worked perfectly. Thanks!
