### ISSUE TITLE
Cannot toggle OpennessState of node that defaulted to closed

### ISSUE THREAD

**Issue by ZakRabe** [Lodin/react-vtree#32]
I am attempting to control the openness state of some nodes under certain conditions in my project.  But I have found this is doesn't seem to work unless all the nodes have `isOpenByDefault: true`

Here is a minimal example I have reproduced that is similar to what I am hoping to achieve. 

https://codesandbox.io/s/admiring-tree-k0x04?file=/src/Tree.tsx

You can see I want to default the root node to be open. and default its direct children to closed. 

Under some circumstance (in this example it's just after the tree has initialized for simplicity), I want to open a node. The Button for the node changed to `-`, as if it thinks its open, but the children do not render. 

There are also some errors in the console that nodes cannot be found. `No record with id child-2 found.`

I also notice if I toggle any of the nodes, the whole tree then updates correctly. In this example, clicking "Child 4", expands Child 4, but also the node I toggled with `opennessState` then renders its children correctly.

Is this a known constraint of the openness state control? or am I trying to approach this in the wrong way?

**Comment by Lodin** [comment]
You can easily fix it by the adding `refreshNodes: true` option after the `opennessState` option:
```js
treeRef.recomputeTree({
  opennessState: {
    "child-1": true
  },
  refreshNodes: true,
});
```

I would name it an API design flaw. I understand that it isn't expected to work this way; the [v3.0](https://github.com/Lodin/react-vtree/milestone/1) should fix it along with other issues.

You can also try the new approach in the [fix/performance-on-big-data](https://github.com/Lodin/react-vtree/tree/fix/performance-on-big-data) branch. See the branch's README for examples.
<details>
<summary>Instructions</summary>

- Clone the repo
- Run the following command:
```bash
$ npm install
$ npm run build
```
- Install the `dist` folder to your project.
</details>

**Comment by ZakRabe** [comment]
Thanks for the feedback. I'll give it a try 👍

**Comment by ZakRabe** [comment]
refreshNodes works for now. Will look to upgrade to 3.0 once its released. thanks again
