### ISSUE TITLE
Can we get More Documentation and a working example of how to use scrollToItem

### ISSUE THREAD

**Issue by jonniedarko** [Lodin/react-vtree#39]
I am finding it difficult to get `scrollToItem` to work, I have the reference to the tree and call `ref.current.scrollToItem(row)` in  but it never seems to scrollToItem (even when all parent nodes are already open)

Also it is unclear to me how we can know the `index` for an item without all its parent nodes already opened as when subtree is collapsed it changes all the index's
I would expect to be able to have an id for a node and if I scroll to said `id` it would open any parent nodes currently closed and scroll to said item

Maybe my expectation/understanding is wrong?

**Comment by Lodin** [comment]
Hi @jonniedarko. 

Could you elaborate a bit more about what do you try to scroll to? Is it an `id` of the tree node (it is the same `id` property of the object you are yielding from the `treeWalker`) or the numeric `index` of the row?

If it is the node `id`, it looks like a bug and I would ask you to provide an example of the broken scroll (e.g. at [Codesandbox](https://codesandbox.io)).

If it is a numeric `index`, unfortunately, `react-vtree` currently does not provide an option to use the original `scrollToItem` method from the `react-window` library.

> I would expect to be able to have an id for a node and if I scroll to said `id` it would open any parent nodes currently closed and scroll to said item

Unfortunately, the `scrollToItem` is not intended to change the openness state of the tree; you have to do it manually. The `id` that should be given to the `scrollToItem` is the same `id` property of the object you are yielding from the `treeWalker` function.
