### ISSUE TITLE
How to specify my nodes with different heights

### ISSUE THREAD

**Issue by DTbelieveIT** [Lodin/react-vtree#4]
Hi , your project is very userful for me , thank you very much.
By the way , Do you have the demo just like nodes with different heights : )

**Comment by Lodin** [comment]
Hi @DTbelieveIT. Thanks for using this project!
Different heights could be found in the current [demo](https://lodin.github.io/react-vtree/). Just click **Knobs** button, enable **Dynamic height** and play with row height (e.g., set it to `60px`). The direct children of `test-0` root will have a different height than others (`30px` vs. `60px`).

**Comment by Lodin** [comment]
I'm going to close this issue. Feel free to reopen it if you need!
