### ISSUE TITLE
Confused about Migrating 2.x.x -> 3.x.x

### ISSUE THREAD

**Issue by intr0** [Lodin/react-vtree#46]
Hi,

On the npm site - https://www.npmjs.com/package/react-vtree-  there is "2.0.4" version visible as the latest one.

I've just installed react-vtree like:
`npm install react-vtree`
and in my package.json I can see:
`"react-vtree": "^2.0.4",`

On the readme page of the react-vtree I can see a note

> NOTE: This is the documentation for version 3.x.x.

 and a migration section - https://github.com/Lodin/react-vtree#migrating-2xx---3xx- 

I tried to adopt my code regardles to the documentation from readme file but I have many issues e.g. isOpen and setOpen are undefined. Then I tried to access "toggle" and this function is available. So it seems that master branch points to version 2 but there is no tag/branch for version 3 in this repo..?

Can  you please tell me how can I download version 3 of react-vtree ?

UPDATE: 
Cloning the repo from master branch, building manually and copying to node_modules delivers version 3 but I'd like to install it from npm, so help still needed here.

**Comment by Lodin** [comment]
Yeah, sorry for the confusion and the long response. I should have published it as a beta version.
It is done now in [3.0.0-beta.0](https://github.com/Lodin/react-vtree/releases/tag/3.0.0-beta.0) release
