### ISSUE TITLE
Async data tree bug

### ISSUE THREAD

**Issue by atarvainen** [Lodin/react-vtree#48]
Hello,

I discovered a bug(?) in v3 async tree. This bug can be replicated in the Async data tree demo.

First if a user opens e.g. three levels of child nodes under a parent, then closes the parent and opens another parent, some of the previous parents nodes pop open as well.

See gif =>

![Tree - Async data ⋅ Storybook - Google Chrome 2021-01-18 12-37-45](https://user-images.githubusercontent.com/33045386/104905108-9419a680-598a-11eb-9483-511362040196.gif)

**Comment by Lodin** [comment]
@atarvainen, thanks, that's definitely a bug. I'll take a look.

**Comment by HeavensRegent** [comment]
@Lodin I'm currently running into the same issue.
I did some digging and I believe I found the bug.

In generateNewTree, when it's traversing over the nodes, it says 
`if (currentRecord.isShown) {
 order.push(currentRecord.public.data.id); 
}`
Meaning it adds it to the list to show regardless of whether or not it's parent is showing

This should take care of that issue it checks to see if there is a parent and if there is, verify my parent is also being shown
if (currentRecord.isShown && (!currentRecord.parent || currentRecord.parent.isShown))

**Comment by HeavensRegent** [comment]
I opened a pull request https://github.com/Lodin/react-vtree/pull/53

**Comment by CoreAutomation-JD** [comment]
Any luck getting the pull request in?

**Comment by CoreAutomation-JD** [comment]
For what it's worth I did some local testing with the PR above - It seems to work as long as you are using a 1-level deep tree structure. If you have children of children, it does not persist all the way back, leaving the root issue still exposed.

**Comment by HeavensRegent** [comment]
How would I go about doing the local testing @CoreAutomation-JD? It's probably a simple thing to do it, but I'm not sure how

**Comment by HeavensRegent** [comment]
Here is the updated pull request https://github.com/Lodin/react-vtree/pull/54

**Comment by Lodin** [comment]
Fixed in #54

**Comment by Lodin** [comment]
Released in `react-vtree@3.0.0-beta.1`. Note that now you need to use the `beta` tag to install the `3.0.0` version because I have released `3.0.0-beta.0` as latest by mistake.
